language: node_js
node_js:
  - "10"
install: npm install
jobs:
  include:
    - stage: "Build"
      script: npm run build
    - stage: "Deploy"
      if: tag IS present
      script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - npm run release -- $TRAVIS_TAG --ci