language: node_js
node_js:
  - "10"
install: npm install
jobs:
  include:
    - stage: "Build"
      script: npm run build
    - stage: "Deploy"
      script: npm run release -- $TRAVIS_TAG --ci
      on:
        tags: true