language: node_js
node_js:
  - "10"
install: npm install
jobs:
  include:
    - stage: "Build"
      script: npm run build
    - stage: "Deploy"
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - npm run release
      if: branch = master AND tag IS blank